In [73]:
from PIL import Image
from operator import truediv
import numpy as np

In [84]:
def confusion_matrix(actual, predicted):
    classes       = np.unique(np.concatenate((actual,predicted)))
    confusion_mtx = np.empty((len(classes),len(classes)),dtype=np.int)
    for i,a in enumerate(classes):
        for j,p in enumerate(classes):
            confusion_mtx[i,j] = np.where((actual==a)*(predicted==p))[0].shape[0]
    return confusion_mtx

In [19]:
os.getcwd()

'C:\\Users\\SBIC-LP-1\\Desktop\\LY\\Gleason'

In [50]:
import os
path = 'C:/Users/SBIC-LP-1/Desktop/LY/Gleason'

In [66]:
val_mask = os.path.join(path + '/Gleason Challenge 2019/train and mask split/val_masks')
mask = sorted(os.listdir(val_mask))

In [58]:
true = []
for i in range(len(mask)):
    item = os.path.join(val_mask,mask[i])
    true.append(item)

In [62]:
pred = []
for i in range(len(mask)):
    item = os.path.join(val_mask,mask[i])
    pred.append(item)

In [64]:
len(true)

44

In [65]:
len(pred)

44

In [69]:
true==pred

True

In [145]:
for i in range(len(true)):
    y_true = Image.open(true[i])
    y_pred = Image.open(pred[i])
    true_labels = np.asarray(y_true, dtype=np.int)
    pred_labels = np.asarray(y_pred, dtype=np.int)
    cm = confusion_matrix(true_labels, pred_labels)
    tp = np.diag(cm)
    acc_global = truediv(np.sum(tp), np.sum(cm))
    prec = list(map(truediv, tp, np.sum(cm, axis=0)))
    rec = list(map(truediv, tp, np.sum(cm, axis=1)))
    iou = list(map(truediv, tp, (np.sum(cm, axis=0) + np.sum(cm, axis=0)-tp)))
    print('--------------------------------------')
    #print('Map: {}'.format(true[i][-30:]))
    #print(cm)
    print('Map: {}\nConfusion Matrix:\n {}\nAccuracy: {}\nPrecision: {}\nRecall: {}\nIoU: {}'.format(true[i][-30:],cm,acc, prec, rec, iou))
    print('Map: {}\nConfusion Matrix:\n {}\nAccuracy: {}\nPrecision: {}\nRecall: {}\nIoU: {}'.format(true[i][-30:],cm,acc, prec, rec, iou),file=open("Pred_measures.txt", "a"))

--------------------------------------
Map: core003_classimg_nonconvex.png
Confusion Matrix:
 [[11427843        0]
 [       0 14786557]]
Accuracy: 1.0
Precision: [1.0, 1.0]
Recall: [1.0, 1.0]
IoU: [1.0, 1.0]
--------------------------------------
Map: core007_classimg_nonconvex.png
Confusion Matrix:
 [[10829932        0        0]
 [       0    54289        0]
 [       0        0 17951619]]
Accuracy: 1.0
Precision: [1.0, 1.0, 1.0]
Recall: [1.0, 1.0, 1.0]
IoU: [1.0, 1.0, 1.0]
--------------------------------------
Map: core009_classimg_nonconvex.png
Confusion Matrix:
 [[10631778        0        0]
 [       0  1952295        0]
 [       0        0 13630327]]
Accuracy: 1.0
Precision: [1.0, 1.0, 1.0]
Recall: [1.0, 1.0, 1.0]
IoU: [1.0, 1.0, 1.0]


KeyboardInterrupt: 